version: '2'
services:
  royopticals-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    restart: always
    volumes:
        - ./data/elasticsearch/:/usr/share/elasticsearch/data/
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - 'ES_JAVA_OPTS=-Xms128m -Xmx128m'
      - 'discovery.type=single-node'
